M48
; DRILL file {KiCad 7.0.1} date Mon Mar  4 12:41:08 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-04T12:41:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.7094Y-4.1466
X4.8826Y-4.1466
T2
X6.9868Y-3.151
X6.9868Y-3.465
T3
X4.377Y-4.319
X4.378Y-2.77
X7.055Y-2.775
X7.06Y-4.323
T0
M30
